import { GeistPixelSquare } from "geist/font/pixel";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import posthog from "@realityware/telemetry";
import { ReactScan } from "@/components/react-scan";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const sacco = localFont({
  src: "../../public/static/fonts/Sacco-SemiBoldCondensed.ttf",
  variable: "--font-sacco",
  declarations: [
    { prop: "ascent-override", value: "90%" },
    { prop: "descent-override", value: "0%" },
  ],
});

export const metadata: Metadata = {
  title: "Realityware",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${GeistPixelSquare.variable} font-pixel-square antialiased`}
      >
        <ReactScan />
        <Toaster />
        {children}
      </body>
    </html>
  );
}
